name: CI/CD Vercel

on:
  push:
    branches:
      - main
      - develop
      - "feature/*"

  pull_request:
    types:
      - opened
      - synchronize

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:

  # ============================================================
  # API - PRODUCTION
  # ============================================================

  # deploy-api-production:
  #   name: Deploy API Production
  #   runs-on: ubuntu-latest
  #   environment: Production

  #   outputs:
  #     api_url: ${{ steps.deploy.outputs.api_url }}

  #   steps:

  #     - name: Checkout
  #       uses: actions/checkout@v6

  #     - name: Install Vercel CLI
  #       run: npm install --global vercel@latest

  #     - name: Deploy API Production
  #       id: deploy
  #       working-directory: api
  #       env:
  #         VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  #         VERCEL_PROJECT_ID: ${{ secrets.VERCEL_API_PROJECT_ID }}
  #       run: |

  #         echo "🚀 Deploy da API..."

  #         API_URL=$(vercel deploy \
  #           --prod \
  #           --yes \
  #           --token="$VERCEL_TOKEN" \
  #           --project="$VERCEL_PROJECT_ID")

  #         echo "======================================"
  #         echo "API URL:"
  #         echo "$API_URL"
  #         echo "======================================"

  #         echo "api_url=$API_URL" >> "$GITHUB_OUTPUT"


  # ============================================================
  # WEB - PREVIEW
  # ============================================================

  deploy-preview:
    name: Deploy Preview

    runs-on: ubuntu-latest
    environment: Production

    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Show API URL
        run: |
          echo "🔗 API URL:"

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy Preview
        working-directory: web
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          if [ -z "$VERCEL_TOKEN" ]; then
            echo "❌ VERCEL_TOKEN não configurado"
            exit 1
          fi

          if [ -z "$VERCEL_PROJECT_ID" ]; then
            echo "❌ VERCEL_WEB_PROJECT_ID não configurado"
            exit 1
          fi

          if [ -z "$API_URL" ]; then
            echo "❌ API_URL não foi recebido do job deploy-api-production"
            exit 1
          fi

          echo "🚀 Deploy Web Preview"
          echo "🔗 API: $API_URL"

          vercel deploy \
            --prod
            --yes \
            --token="$VERCEL_TOKEN" \
            --project="$VERCEL_PROJECT_ID"


  # ============================================================
  # WEB - PRODUCTION
  # ============================================================

  deploy-production:
    name: Deploy Web Production

    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    runs-on: ubuntu-latest
    environment: Production

    steps:

      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy Production
        working-directory: web
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          # VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEB_PROJECT_ID }}
          # API_URL: ${{ needs.deploy-api-production.outputs.api_url }}
        run: |
          if [ -z "$VERCEL_TOKEN" ]; then
            echo "❌ VERCEL_TOKEN não configurado"
            exit 1
          fi

          if [ -z "$VERCEL_PROJECT_ID" ]; then
            echo "❌ VERCEL_WEB_PROJECT_ID não configurado"
            exit 1
          fi

          echo "🚀 Deploy Web Production"
          echo "🔗 API: $API_URL"

          vercel deploy \
            --prod \
            --yes \
            --token="$VERCEL_TOKEN" \
            --project="$VERCEL_PROJECT_ID"
